name: Code Quality Check

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: invoke linting agent
        id: eslint
        if: github.event_name == 'pull_request'
        run: |
          curl -f -x POST  -H "Content-Type: application/json" 
            -d "{\"pull_request_number\":${{ github.event.pull_request.number }}\"}"
            https://always-childhood-anything.ngrok-free.dev/webhook/91120b2d-b202-4701-8137-f34da50a222e 